import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import UpperHeader from "@/components/navbar/UpperHeader";
import Hero from "@/components/Hero/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-ull">
          <div className=" flex   flex-col z-[100] items-center   relative">

            <Navbar />
          </div>
          <div className="relative w-full  xl:p-0 m-auto">
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
