import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import UpperHeader from "@/components/navbar/UpperHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="w-full flex flex-col z-[100] items-center   relative  ">
          <div className="bg-black fixed w-full p-[10px] px-[25px]  xl:py-[10px] xl:px-0  ">
            <UpperHeader />

          </div>
          
          <div className="mt-[40px] bg-white md-[44px] fixed w-full px-[25px] xl:p-0 max-w-[1400px] m-auto">
            <Navbar />
          </div>
        </div>
        <div className="max-w-[1400px] relative w-full px-[25px] xl:p-0 m-auto">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
